name: Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm ci

      - run: >-
          npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
          Project is not formatted. Please run "npm run format".' && false)
  tests-local:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Restore node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          # Bump the number after `lit-element-1.x-node-modules` to force a
          # cache update. Note there are cache actions in other jobs in this
          # file that should all keep keys in sync.
          key: lit-element-1.x-node-modules-0-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: NPM install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install XVFB
        run: sudo apt-get install xvfb

      - name: Build
        run: npm run build

      - name: Test
        run: xvfb-run npx wct --npm

  tests-sauce:
    # We can't run Sauce tests on PRs from forked repos, since they don't have
    # access to secrets.
    if: github.event.pull_request == null || github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Restore node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          # Bump the number after `lit-element-1.x-node-modules` to force a
          # cache update. Note there are cache actions in other jobs in this
          # file that should all keep keys in sync.
          key: lit-element-1.x-node-modules-0-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: NPM install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        # This list of browsers originally included 'os x 10.12/safari@10' and
        # 'Linux/firefox', but these browsers both time out after running all
        # tests. This doesn't happen locally, so I'm not sure what's different
        # in GitHub actions that would break this.
        run: >
          npx wct --npm
          -s 'windows 10/microsoftedge@15'
          -s 'windows 10/microsoftedge@17'
          -s 'windows 8.1/internet explorer@11'
          -s 'os x 10.11/safari@9'
          -s 'macos 10.13/safari@11'
          -s 'Linux/chrome@41'
